### ISSUE TITLE
ImportError "normalize" in djangodevkit.serve after upgrading Django 1.8 to 1.9

### ISSUE THREAD

**Issue by wmai** [bearstech/DjangoDevKit#6]
After upgrading Django from 1.8 to 1.9, I get this error when django-serve is executed.

```
Traceback (most recent call last):
  File "bin/django-serve", line 98, in <module>
    import djangodevkit.serve
  File "/Users/wmai/Laboratory/allmecen/eggs/DjangoDevKit-1.0.6-py2.7.egg/djangodevkit/serve.py", line 9, in <module>
    from optparse import OptionParser
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 419, in <module>
    _builtin_cvt = { "int" : (_parse_int, _("integer")),
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 569, in gettext
    return dgettext(_current_domain, message)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 533, in dgettext
    codeset=_localecodesets.get(domain))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 468, in translation
    mofiles = find(domain, localedir, languages, all=1)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 440, in find
    for nelang in _expand_lang(lang):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 133, in _expand_lang
    from locale import normalize
ImportError: cannot import name normalize
```

Can someone help me out? I don't know the correct course to take here. 

Thanks,
William

**Comment by wmai** [comment]
Problem solved. I had to delete `__init__.py` and `__init__.pyc` inside the folder `locale`.
